from PyQt5.QtWidgets import (QApplication, QWidget, QPushButton, QLineEdit, QGridLayout)

class MainWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('Calculator')

        self.display = QLineEdit()
        self.display.setReadOnly(True)

        button1 = QPushButton('0')
        button2 = QPushButton('1')
        button3 = QPushButton('2')
        button4 = QPushButton('3')
        button5 = QPushButton('4')
        button6 = QPushButton('5')
        button7 = QPushButton('6')
        button8 = QPushButton('7')
        button9 = QPushButton('8')
        button10 = QPushButton('9')
        button11_b = QPushButton('<-')
        button12_C = QPushButton('C')
        button13_p = QPushButton('+')
        button14_m = QPushButton('-')
        button15_u = QPushButton('*')
        button16_d = QPushButton('/')
        button17_r = QPushButton('=')
        button18_p = QPushButton('.')

        layout = QGridLayout()
        layout.addWidget(self.display, 0, 0, 1, 4)
        layout.addWidget(button1, 5, 0)
        layout.addWidget(button2, 4, 0)
        layout.addWidget(button3, 4, 1)
        layout.addWidget(button4, 4, 2)
        layout.addWidget(button5, 3, 0)
        layout.addWidget(button6, 3, 1)
        layout.addWidget(button7, 3, 2)
        layout.addWidget(button8, 2, 0)
        layout.addWidget(button9, 2, 1)
        layout.addWidget(button10, 2, 2)
        layout.addWidget(button11_b, 1, 0)
        layout.addWidget(button12_C, 1, 1)
        layout.addWidget(button13_p, 1, 2)
        layout.addWidget(button14_m, 1, 3)
        layout.addWidget(button15_u, 2, 3)
        layout.addWidget(button16_d, 3, 3)
        layout.addWidget(button17_r, 5, 1)
        layout.addWidget(button18_p, 5, 2)

        self.setLayout(layout)

app = QApplication([])
window = MainWindow()
window.show()
app.exec_()
